apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-ingress
  namespace: personal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

spec:
  ingressClassName: nginx
  rules:
    - host: portfolio.ngtantai.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 80
    - host: curriculum-vitae.ngtantai.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curriculum-vitae-service
                port:
                  number: 80