# storageclass-local.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---

# PVs cho Node kubernete-1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete-1-data1
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-1"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete-1-data2
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-1"]
---
# PVs cho Node kubernete2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete2-data1
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete2"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete2-data2
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete2"]
---
# PVs cho Node kubernete-3
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete-3-data1
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-3"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-kubernete-3-data2
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-3"]
---
# PV nhỏ cho PVC logs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-logs
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-1"]
---
# PV nhỏ cho PVC metrics
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-metrics
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  storageClassName: minio-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/minio-data/metrics
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["kubernete-1"]