# Deployment for portfolio app
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio
  name: portfolio-deployment
  namespace: personal
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portfolio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portfolio
      namespace: personal
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - image: harbor.ngtantai.pro/personal/portfolio:250712-193104
        imagePullPolicy: Always
        name: portfolio
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: HARBOR_REGISTRY
          value: "harbor.ngtantai.pro"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
---
# Service cho portfolio frontend
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: personal
  labels:
    app: portfolio
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP